INSERT INTO `estado` (`id_pais`, `nombre`, `abrev`) VALUES
(1, 'Aguascalientes', 'Ags.'),
(1, 'Baja California', 'BC'),
(1, 'Baja California Sur', 'BCS'),
(1, 'Campeche', 'Camp.'),
(1, 'Coahuila de Zaragoza', 'Coah.'),
(1, 'Colima', 'Col.'),
(1, 'Chiapas', 'Chis.'),
(1, 'Chihuahua', 'Chih.'),
(1, 'Distrito Federal', 'DF'),
(1, 'Durango', 'Dgo.'),
(1, 'Guanajuato', 'Gto.'),
(1, 'Guerrero', 'Gro.'),
(1, 'Hidalgo', 'Hgo.'),
(1, 'Jalisco', 'Jal.'),
(1, 'México', 'Mex.'),
(1, 'Michoacán de Ocampo', 'Mich.'),
(1, 'Morelos', 'Mor.'),
(1, 'Nayarit', 'Nay.'),
(1, 'Nuevo León', 'NL'),
(1, 'Oaxaca', 'Oax.'),
(1, 'Puebla', 'Pue.'),
(1, 'Querétaro', 'Qro.'),
(1, 'Quintana Roo', 'Q. Roo'),
(1, 'San Luis Potosí', 'SLP'),
(1, 'Sinaloa', 'Sin.'),
(1, 'Sonora', 'Son.'),
(1, 'Tabasco', 'Tab.'),
(1, 'Tamaulipas', 'Tamps.'),
(1, 'Tlaxcala', 'Tlax.'),
(1, 'Veracruz de Ignacio de la Llave', 'Ver.'),
(1, 'Yucatán', 'Yuc.'),
(1, 'Zacatecas', 'Zac.');